#1 resolvido outro erro de modelagem
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Event|event, expression 'Participation' failed to locate a name ("name 'Participation' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.mod_events.models.Event'> class after both dependent classes have been defined.